name: Robot Framework CI (manual)

on:
  workflow_dispatch:
    inputs:
      suite:
        description: 'Which tests to run (path or folder)'
        required: true
        default: 'tests'
      browser:
        description: 'Browser to use'
        required: true
        default: 'chrome'
      headless:
        description: 'Run headless? true/false'
        required: true
        default: 'true'

jobs:
  run-robot:
    runs-on: ubuntu-latest

    services:
      selenium:
        image: selenium/standalone-chrome:latest
        ports:
          - 4444:4444
        options: >-
          --shm-size=2g
          --health-cmd="curl -f http://localhost:4444/wd/hub/status || exit 1"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install robotframework
          pip install robotframework-seleniumlibrary

      - name: Run Robot Framework tests on Selenium Grid
        env:
          SELENIUM_GRID_URL: http://localhost:4444/wd/hub
        run: |
          echo "Running suite: ${{ github.event.inputs.suite }}"
          robot --outputdir results \
            -v BROWSER:${{ github.event.inputs.browser }} \
            -v HEADLESS:${{ github.event.inputs.headless }} \
            -v SELENIUM_GRID_URL:${SELENIUM_GRID_URL} \
            ${{ github.event.inputs.suite }}

      - name: Upload Robot results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: robot-results
          path: results/
